### ISSUE TITLE
Consider enabling ivy

### ISSUE THREAD

**Issue by rski** [josteink/emacs-oob-reboot#20] opened 2017-05-06 06:50 UTC
It is in elpa http://elpa.gnu.org/packages/ivy.html

Ivy's behaviour feels a lot more like a modern editor's behaviour does compared to the default Emacs behaviour. It could be enabled in a way such that people who don't want to use it can easily disable it, something along the lines of 

`(unless do-not-enable-ivy-mode (ivy-mode 1))`

**Comment by brotzeit** [comment] 2017-05-06 07:45
I prefer helm, but I also think ivy would a better default.

**Comment by angrybacon** [comment] 2017-05-06 08:26
I also prefer Helm, but the choice between nothing, Ido, Ivy and Helm seems a little too opinionated to be made by anyone else but the user.

**Comment by brotzeit** [comment] 2017-05-06 10:07
Whatever it will be, it should be more than now. But helm is definitely not a good choice. I also think emacs should provide more possibilities to use the mouse. I don't use my mouse in emacs, but for new users it would make things a lot easier.

**Comment by dchrzanowski** [comment] 2017-05-06 10:16
I feel like any completion system would be better than what it is now. Possibly the option would be to make a poll and just put it up to vote? I mean the choice between Ivy, Helm, Ido

**Comment by rski** [comment] 2017-05-06 10:21
helm is not on Elpa, so that probably disqualifies from the get go.

**Comment by brotzeit** [comment] 2017-05-06 10:25
I guess most users will vote for their own preference instead of choosing the most newcomer friendly settings. Packages like helm need time to get used to it and require basic knowledge of customizing emacs.

**Comment by rski** [comment] 2017-05-06 10:32
@brotzeitmacher I think you are right on the voting thing. I don't use ivy, but i proposed it as the simplest, most newcomer friendly  way to get a powerful feature out of the box, namely completion for emacs commands.

**Comment by dchrzanowski** [comment] 2017-05-06 10:43
Maybe with enough push some of those packages could become a part of Emacs as standard? As a new user you have no clue of how much stuff there is in M-x , once a completion system is installed the realization of how much there is and how easily it can be found, suddenly appears! The next realization usually is "Oh I can bind these commands to my keys" and the tinkering starts. Thus  a completion system out of the box I would consider an absolute necessity!

**Comment by angrybacon** [comment] 2017-05-06 10:46
But there **is** completion by default. It's just not interactive.

Of the 3, Ido is probably the least intrusive although I believe there's a way to make Ivy look like Ido. Least intrusive because it's doesn't change the configuration of windows like default completion and Helm do.

**Comment by dchrzanowski** [comment] 2017-05-06 11:53
@angrybacon yes there is, but as you said, it isn't great. Personally I would like put a forward ido or ivy due to more of a friendly feel to it all.

**Comment by mookid** [comment] 2017-05-06 13:33
I think that one important point is that Ido is shipped with emacs.

**Comment by justinjk007** [comment] 2017-05-06 13:40
People can vote here https://strawpoll.com/aweaz53

**Comment by mguzmann** [comment] 2017-05-06 16:03
is it likely though that they'll include something like ivy as a default?

**Comment by justinjk007** [comment] 2017-05-06 16:06
Well...ivy is on elpa... ¯\_(ツ)_/¯

**Comment by bretfh** [comment] 2017-05-06 16:17
Angrybacon brings up a good point. The choice for packages in emacs is opinionated. Maybe were going the wrong way in creating a better default by selecting what we think is best for the user. 

How could we make emacs a better environment for learning about emacs itself and how to change it so the user can make these decisions?

**Comment by mguzmann** [comment] 2017-05-06 16:25
I know people who've been put off by the horrible defaults.

**Comment by bretfh** [comment] 2017-05-06 16:29
Exactly. So why not introduce emacs as what it is? A programmable editor to suite your needs. This wont appeal to everyone but nothing ever should. This approach just makes it clear to the user what emacs is about upon starting it. When I was new I had no idea what emacs was capable of when I first opened it. It took quite a bit of time to see why it was worth the investment.

**Comment by rski** [comment] 2017-05-06 17:21
@angrybacon I see your point, but imo

- having to press TAB is not the most newcomer friendly thing
- ido is not that powerful, to get it working with M-x it seems you either have to copy a bunch of code  from the wiki or use smex . not that newcomer friendly either
- helm is not on elpa so that is not an option really
- ivy is on elpa and it is quite easy to use for begginers. Sure it is definitely opinionated, but Emacs comes with flymake. People who want to use flycheck end up doing so anyway. Being opinionated  might not be as much of a problem as it seems, as long as disabling ivy is really easy.

**Comment by angrybacon** [comment] 2017-05-06 17:50
@rski Likewise I don't see any issue leaving Emacs as is, given enabling Ivy is really easy too. 

Actually I think <kbd>Tab</kbd> is very intuitive to complete something: IRC clients, browsers, more generally anything that we use daily with a search bar.

**Comment by rski** [comment] 2017-05-06 17:56
Browsers start suggesting URLs as soon as you start typing, I can't remember having to press tab in a browser any time recently.

**Comment by angrybacon** [comment] 2017-05-06 18:09
@rski My point was that people have associated <kbd>Tab</kbd> -- within an input box -- with "Complete this for me".

**Comment by dchrzanowski** [comment] 2017-05-06 18:31
It is a better solution to have suggestions as you type, you also have the added benefit of using TAB anyway!

Other aspect of "completion as you type"  is that you see similar commands, I've discovered dozens of cool functions by seeing them by accident as I was typing something into M-x with helm.

**Comment by rski** [comment] 2017-05-06 19:34
yeah i spent ages looking at commands via M-x after installing helm, it was massively helpful

**Comment by bretfh** [comment] 2017-05-06 20:19
Tab completion is nearly universal.

**Comment by dchrzanowski** [comment] 2017-05-06 22:53
@whtfox we are not saying that it isn't, we are saying that a better idea would be to have both TAB and "complete as I type", kinda something like helm can provide

**Comment by bretfh** [comment] 2017-05-07 01:19
Apologies. Miss read.

**Comment by rski** [comment] 2017-05-07 17:28
One more thing about the autocompletion:

Doing M-x region TAB returns nothing 

Doing M-x region with ivy shows all the commands that act on regions, making it closer to appropos.

**Comment by alandmoore** [comment] 2017-05-15 14:35
Between nothing, `ido`, and `ivy`, I think `ivy` is the best choice.  Never used it before today, but I think it improves command discoverability singificantly.

The problem with `ido` is that the completion does a "starts-with" match rather than a "contains" match.  So quite often I might be hunting for a command that operates on "foo", but the command I need is called "do-something-to-foo-with-condition-bar".  I'll never locate that command with `ido`, but I would with `ivy`.

As for doing nothing... I guess the operative question is whether command discoverability is a problem that needs solving.  As a user of many years who *still* needs to go hunting for commands on a regular basis (for which I use `helm`, but that's moot because MELPA), I would contend that it is.

**Comment by jackrusher** [comment] 2017-05-15 15:44
Emacs without something like `ido`/`ivy`/`helm` is just unnecessary cruelty.

**Comment by angrybacon** [comment] 2017-05-15 15:47
@alandmoore Did you actually need that discoverability as you were starting out with Emacs? Legit question, I know I didn't personally.

**Comment by alandmoore** [comment] 2017-05-15 20:21
@angrybacon  Well it would have saved me a lot of googling, scanning through apropos buffers, and doing things in very inefficient ways over the years.   Being turned on to `ido` or `helm` made a huge difference in my ability to find the functionality I was looking for.

*Did* I need it?  I *still* need it!  

I know, for example, that there's an emacs function for converting Windows line endings to Unix line endings.  Or a function to show me tabs vs. spaces.  Can't remember the name of either.  I maybe use those functions 4 or 5 times a year, and every time I have to look it up.

Could I just use `command-apropos` to find commands, and then manually retype them?  I suppose, but why not provide those results in a way that's less tedious to use?  This is pretty much exactly what `ivy-mode` et al are doing.

**Comment by phillord** [comment] 2017-05-15 20:48
I love ido and think it's fantastic. Helm has it's place as well. Not tried ivy yet.

My concern with the two I have tried, is that they are complex and confusing in terms of what they are achieving. Helm took my three or four attempts because I found the first experience so jarring. And I have two decades worth of Emacs experience.

However, because I have two decades worth of Emacs experience, my opinions are worth very little. If we seriously want to consider this, then we need to test it on new Emacs users, and write up the stories of how well they took to it. Building up this sort of evidence base will move us forward.

**Comment by angrybacon** [comment] 2017-05-15 20:54
@alandmoore I totally get what you mean. My point was that until you want to tinker around you don't necessarily need the ability to fuzzy search things around.

I'm only asking because I don't have an opinion on the subject: as a complete novice, is the discoverability really worth it or would it just be overwhelming?

But like @phillord said, we probably won't know until we see actual novice users actually try it.

**Comment by josteink** [comment] 2017-05-16 05:20
> Did you actually need that discoverability as you were starting out with Emacs? Legit question, I know I didn't personally.

My experience as someone new to *VS Code* and *Sublime Edit* was that putting the available commands front and centre like this made functionality I would otherwise had to Google for almost immediately available.

Given a good implementation, functionality like this can IMO be very empowering to new users.

**Comment by jackrusher** [comment] 2017-05-16 06:10
I've introduced a couple dozen young developers to emacs in the last five years. The use of a completion framework makes a day/night difference in this process.

**Comment by daveliepmann** [comment] 2017-05-16 06:48
Emacs without command autocompletion is an outdated out-of-the-box experience. The computer knows what commands there are. Noobs don't. 

It's sadistic to not provide some default command autocompletion. This is discoverability 101.

**Comment by phillord** [comment] 2017-05-16 08:19
@jackrusher When you "introduced" them, did you explain it or just turn it on and leave them to it?

@daveliepmann "autocompletion" is not a single thing. In buffer word completion, versus command completion for a start. Discoverability 101 is, for me, the menu system. But, regardless, we need data, not your experience.

**Comment by jackrusher** [comment] 2017-05-16 08:23
My attempts at "turn it on and leave them to it" (which really meant "they use 'brew install' and give it a go") _universally failed_ without also giving them a config that (a) normalized key bindings toward their platform expectations and (b) made discovery easier.

**Comment by daveliepmann** [comment] 2017-05-16 10:08
Sorry, I meant "command auto-completion" in both my references to
autocompletion above. In the context of this thread that was intended to
throw vigorous support behind "any solution but 'none'".

**Comment by justinjk007** [comment] 2017-05-16 11:50
So I guess we can all agree on enabling Ivy with the default bindings @abo-abo recommends.

**Comment by abo-abo** [comment] 2017-05-16 12:33
Since I'm pinged, I here's what I think:

1. Ask hundreds of thousands of programmers what they adore about IntelliJ: it's completion and discoverability (meaning that all completion methods are also accessible through the menu). Without completion no serious programming environment can ever truly take off.
2. Ivy is on GNU ELPA; `0.9.1` was released just a month ago.
3. Ivy is comparable to Helm; being similarly powerful, the choice between the two is mostly about the look-and-feel personal preferences. But adding Ido to that group is a bad joke: Ido is severely less powerful than either Ivy or Helm; it's not even close.
4. For ~6 years I've had <kbd>C-t</kbd> bound to `smex` / `helm-M-x` / `counsel-M-x`. I highly recommend this setup. I don't miss `transpose-chars`.

**Comment by phillord** [comment] 2017-05-22 12:45
I've been trying ivy out for the last few days, and while it is very nice, I do still find that, pretty frequently, I end up in a WTF situation. Now, of course, this is partly because I am a long term ido user, and I still find it quicker than anything for file system navigation. So I do worry that something like ivy will increase the dissonance new users get when trying out Emacs for the first time. Clearly,though, it saves an awful lot of time.

**Comment by abo-abo** [comment] 2017-05-22 16:08
@phillord Strange. I've been an Ido user for a long time too. And many things `counsel-find-file` does are attempts to "fix" `ido-find-file`.

One of the biggest points of dissonance and discomfort with Ido for me was the <kbd>C-f</kbd> binding. While normally it should be `forward-char`, in Ido it's the "I give up" button of the completion interface.  It means Ido has failed and a fall back to default completion is the only way to recover. And I didn't accept that design for Ivy: there should be no reason to want to drop out of completion.  Ivy has the <kbd>C-M-j</kbd> binding, but even then you might get some help from the completion system before you press that.

I've worked to provide convenience for all common workflows in file system navigation: two years of bug fixing iterations should have covered it. For instance, try `/ssh:` completion: I don't think Ido ever had that figured out.

**Comment by phillord** [comment] 2017-05-24 16:11
Oleh Krehel <notifications@github.com> writes:

> @phillord Strange. I've been an Ido user for a long time too. And many things
> `counsel-find-file` does are attempts to "fix" `ido-find-file`.
>
> One of the biggest points of dissonance and discomfort with Ido for me was the
> <kbd>C-f</kbd> binding. While normally it should be `forward-char`, in Ido
> it's the "I give up" button of the completion interface.  It means Ido has
> failed and a fall back to default completion is the only way to recover. And I
> didn't accept that design for Ivy: there should be no reason to want to drop
> out of completion.  Ivy has the <kbd>C-M-j</kbd> binding, but even then you
> might get some help from the completion system before you press that.
>
> I've worked to provide convenience for all common workflows in file system
> navigation: two years of bug fixing iterations should have covered it. For
> instance, try `/ssh:` completion: I don't think Ido ever had that figured out.


My point is not to compare ivy or ido -- I am fully aware that the
things that are annoying me about ivy are because ido is burnt into my
fingers; for example, from any directory, typing ~/src in ido works, but
breaks in ivy, where you have to use ~src. Which is right? Well, it's
not the point.

I just worry that for new users, completion is going to confuse
things. Making completion regular WRT Emacs conventions does not help in
the user does not understand Emacs conventions.

Also always, trying this out with new users is the way to answer the
question -- that is users new to Emacs, not new to ivy.

**Comment by josteink** [comment] 2023-10-11 07:13
I think recent changes to Emacs (eglot, tree-sitter, etc) has helped make Emacs much more usable OOB. Considering repo-purpose obsolete.

Closing all issues and archiving repo. Thanks to all contributors!

**Closed as completed by josteink** 2023-10-11 07:13 UTC
